services:
  cookieconsent.assets.cookieconsent:
    class: ACP3\Core\Assets\Entity\LibraryEntity
    arguments:
      - "consentManager"
      - false
      - []
      - []
      - ["klaro.js"]
      - "cookieconsent"
      - false
    tags:
      - { name: "acp3.assets.library" }
