services:
  _defaults:
    autowire: true
    bind:
      $coreCachePool: "@core.cache_item_pool"

  ACP3\Core\Assets\EventListener\StaticAssetsListener:
    tags:
      - { name: kernel.event_subscriber }

  ACP3\Core\Assets: ~

  tubalmartin\CssMin\Minifier: ~

  ACP3\Core\Assets\Renderer\Strategies\CSSRendererStrategy: ~
  ACP3\Core\Assets\Renderer\Strategies\ConcatCSSRendererStrategy:
    decorates: ACP3\Core\Assets\Renderer\Strategies\CSSRendererStrategy
  ACP3\Core\Assets\Renderer\Strategies\CSSRendererStrategyInterface: '@ACP3\Core\Assets\Renderer\Strategies\CSSRendererStrategy'

  ACP3\Core\Assets\Renderer\Strategies\JavaScriptRendererStrategy: ~
  ACP3\Core\Assets\Renderer\Strategies\CachingJavaScriptRendererStrategy:
    decorates: ACP3\Core\Assets\Renderer\Strategies\JavaScriptRendererStrategy
  ACP3\Core\Assets\Renderer\Strategies\JavaScriptRendererStrategyInterface: '@ACP3\Core\Assets\Renderer\Strategies\JavaScriptRendererStrategy'

  ACP3\Core\Assets\FileResolver\:
    resource: "../../../src/Assets/FileResolver/"

  ACP3\Core\Assets\FileResolver:
    calls:
      - addStrategy: ['@ACP3\Core\Assets\FileResolver\TemplateFileCheckerStrategy']
      - addStrategy: ['@ACP3\Core\Assets\FileResolver\AssetsManifestFileCheckerStrategy']
      - addStrategy: ['@ACP3\Core\Assets\FileResolver\MinifiedAwareFileCheckerStrategy']
      - addStrategy: ['@ACP3\Core\Assets\FileResolver\StraightFileCheckerStrategy']

  ACP3\Core\Assets\IncludeJs: ~
  ACP3\Core\Assets\IncludeStylesheet: ~

  ACP3\Core\Assets\Libraries: ~

  core.assets.libraries.cache_item_pool:
    class: Psr\Cache\CacheItemPoolInterface
    factory: "@Psr6CacheItemPoolFactory"
    arguments: ["libraries"]
    tags:
      - { name: acp3.cache_item_pool }

  ACP3\Core\Assets\LibrariesCache:
    arguments:
      $librariesCachePool: "@core.assets.libraries.cache_item_pool"

  ACP3\Core\Assets\PageCssClasses: ~

  ACP3\Core\Assets\Renderer\CSSRenderer:
  ACP3\Core\Assets\Renderer\JavaScriptRenderer:
