<?php
define('INSTALLED', true);
define('DEBUG', true);
define('CONFIG_CACHE_IMAGES', true);
define('CONFIG_CACHE_MINIFY', 3600);
define('CONFIG_DATE_DST', 0);
define('CONFIG_DATE_FORMAT_LONG', 'd.m.y, H:i');
define('CONFIG_DATE_FORMAT_SHORT', 'd.m.y');
define('CONFIG_DATE_TIME_ZONE', 3600);
define('CONFIG_DB_HOST', 'localhost');
define('CONFIG_DB_NAME', 'acp3');
define('CONFIG_DB_PASSWORD', '');
define('CONFIG_DB_PRE', 'acp3_');
define('CONFIG_DB_USER', 'root');
define('CONFIG_DB_VERSION', 13);
define('CONFIG_DESIGN', 'acp3');
define('CONFIG_ENTRIES', 20);
define('CONFIG_FLOOD', 30);
define('CONFIG_HOMEPAGE', 'news/list/');
define('CONFIG_LANG', 'de');
define('CONFIG_MAILER_SMTP_AUTH', false);
define('CONFIG_MAILER_SMTP_HOST', '');
define('CONFIG_MAILER_SMTP_PASSWORD', '');
define('CONFIG_MAILER_SMTP_PORT', 25);
define('CONFIG_MAILER_SMTP_SECURITY', 'none');
define('CONFIG_MAILER_SMTP_USER', '');
define('CONFIG_MAILER_TYPE', 'mail');
define('CONFIG_MAINTENANCE_MESSAGE', 'Wegen kurzfristigen Wartungsarbeiten ist diese Website zur Zeit nicht erreichbar. Bitte versuchen Sie es in einigen Minuten erneut.');
define('CONFIG_MAINTENANCE_MODE', false);
define('CONFIG_SEO_ALIASES', true);
define('CONFIG_SEO_META_DESCRIPTION', '');
define('CONFIG_SEO_META_KEYWORDS', '');
define('CONFIG_SEO_MOD_REWRITE', false);
define('CONFIG_SEO_TITLE', 'ACP3');
define('CONFIG_VERSION', '4.0 SVN');
define('CONFIG_WYSIWYG', 'ckeditor');
?>